{
  "hash": "3889cad85edb3fb242171a307a98bd5a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Analysis of postural sway data\"\nauthor: \"Steve Simon and Leroy Wheeler\"\nformat: \n  html:\n    embed-resources: true\ndate: 2024-10-09\n---\n\n\n\nThis program reads data and runs a two-sample t-test. Consult the [data dictionary][dic] for information about the data itself.\n\n[dic]: https://github.com/pmean/data/blob/main/files/postural-sway.yaml\n\n## Libraries\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(broom)\nlibrary(tidyverse)\n```\n:::\n\n\n\n## Read data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsway <- read_tsv(\n  file=\"../data/postural-sway.txt\",\n  col_types=\"cnn\")\nnames(sway) <- tolower(names(sway))\nglimpse(sway)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 17\nColumns: 3\n$ age      <chr> \"Elderly\", \"Elderly\", \"Elderly\", \"Elderly\", \"Elderly\", \"Elder…\n$ fbsway   <dbl> 19, 30, 20, 19, 29, 25, 21, 24, 50, 25, 21, 17, 15, 14, 14, 2…\n$ sidesway <dbl> 14, 41, 18, 11, 16, 24, 18, 21, 37, 17, 10, 16, 22, 12, 14, 1…\n```\n\n\n:::\n:::\n\n\n\n## Boxplot of fbsway by age\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsway |>\n  ggplot(aes(age, sidesway)) +\n    geom_boxplot() +\n    ggtitle(\"Graph drawn by Leroy Wheeler on 2024-10-09\") +\n    xlab(\"Treatment group\") +\n    ylab(\"Side to side sway\") +\n    coord_flip()\n```\n\n::: {.cell-output-display}\n![](wheeler-5501-08-sway_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n\nThe elderly patients have generally higher side to side sway values. The elderly group also appear to have more variation which include two extreme outliers.\n\n## Descriptive statistics for memory by treatment\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsway |>\n  group_by(age) |>\n  summarize(\n    sidesway_mn=mean(sidesway),\n    sidesway_sd=sd(sidesway),\n    n=n())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  age     sidesway_mn sidesway_sd     n\n  <chr>         <dbl>       <dbl> <int>\n1 Elderly        22.2       10.3      9\n2 Young          15.1        3.91     8\n```\n\n\n:::\n:::\n\n\n\nThe average side-to-side sway is higher in the elderly patients. There is more variation in the elderly group, possibly caused by the two outliers.\n\n## Two-sample t-test\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1 <- t.test(\n  sidesway ~ age, \n  data=sway,\n  alternative=\"two.sided\",\n  var.equal=TRUE)\nm1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  sidesway by age\nt = 1.8349, df = 15, p-value = 0.08643\nalternative hypothesis: true difference in means between group Elderly and group Young is not equal to 0\n95 percent confidence interval:\n -1.146965 15.341409\nsample estimates:\nmean in group Elderly   mean in group Young \n             22.22222              15.12500 \n```\n\n\n:::\n:::\n\n\nThe 95% confidence interval includes the value of zero for the difference in the sample means of sidesway values. Further, the calculated p value is greater than our alpha which is set at 0.05. Therefore we conclude that there is not enough difference in the sample means to support rejecting the null hypothesis.\n\n\n## Equivalent analysis using linear regression\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm2 <- lm(sidesway ~ age, data=sway)\ntidy(m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic     p.value\n  <chr>          <dbl>     <dbl>     <dbl>       <dbl>\n1 (Intercept)    22.2       2.65      8.38 0.000000487\n2 ageYoung       -7.10      3.87     -1.83 0.0864     \n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                2.5 %    97.5 %\n(Intercept)  16.56676 27.877688\nageYoung    -15.34141  1.146965\n```\n\n\n:::\n:::\n\n\nUsing a linear model, R program has given a value of zero to the elderly group and a value of one to the young group.  The y-intercept is equivalent to the mean sidesway of the elderly group and has a value of 22.2.  The young group mean value is determined by adding -7.09 to the elderly group mean and is equal to 15.1. The 95% confidence interval includes the possibility that the difference between the two means is zero so there is not enough difference between the two sample means to support rejecting the null hypothesis.  \n\n",
    "supporting": [
      "wheeler-5501-08-sway_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}