{
  "hash": "5dedaa0b1abb79d86d257a615fab92fe",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Linear regression modules using the fev dataset\"\nauthor: \"Steve Simon\"\nformat: \n  html:\n    embed-resources: true\ndate: 2024-09-25\n---\n\n\n\nThere is a [data dictionary][dd] that provides more details about the data. The program was written by Steve Simon on 2024-09-02 and is placed in the public domain.\n\n[dd]: https://github.com/pmean/datasets/blob/master/fev.yaml\n\n## Libraries\n\nYou should always load the tidyverse library. The broom library provides the glance, tidy, and augment functions that help you with computations of linear regression models. The car library provides the vif function for measuing collinearity.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(broom)\nlibrary(car)\nlibrary(tidyverse)\n```\n:::\n\n\n\n## List variable names\n\nSince the variable names are not listed in the data file itself, you need to list them here.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npulmonary_names <- c(\n    \"age\",\n    \"fev\",\n    \"height\",\n    \"sex\",\n    \"smoke\")\n```\n:::\n\n\n\n## Reading the data\n\nHere is the code to read the data and show a glimpse. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npulmonary <- read_csv(\n  file=\"../data/fev.csv\",\n  col_names=pulmonary_names,\n  col_types=\"nnncc\")\nglimpse(pulmonary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 654\nColumns: 5\n$ age    <dbl> 9, 8, 7, 9, 9, 8, 6, 6, 8, 9, 6, 8, 8, 8, 8, 7, 5, 6, 9, 9, 5, …\n$ fev    <dbl> 1.708, 1.724, 1.720, 1.558, 1.895, 2.336, 1.919, 1.415, 1.987, …\n$ height <dbl> 57.0, 67.5, 54.5, 53.0, 57.0, 61.0, 58.0, 56.0, 58.5, 60.0, 53.…\n$ sex    <chr> \"F\", \"F\", \"F\", \"M\", \"M\", \"F\", \"F\", \"F\", \"F\", \"F\", \"F\", \"M\", \"F\"…\n$ smoke  <chr> \"N\", \"N\", \"N\", \"N\", \"N\", \"N\", \"N\", \"N\", \"N\", \"N\", \"N\", \"N\", \"N\"…\n```\n\n\n:::\n:::\n\n\n\n## m1: Linear regression model using sex to predict fev\n\nIs there a relationship between sex and fev? Do males tend to have larger fev values than females. This section (labelled m1) shows some simple descriptive and graphical summaries followed by a linear regression model.\n\n## m1: Descriptive stastics for sex\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npulmonary |>\n\tcount(sex) |>\n\tmutate(total=sum(n)) |>\n\tmutate(pct=100*n/total)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  sex       n total   pct\n  <chr> <int> <int> <dbl>\n1 F       318   654  48.6\n2 M       336   654  51.4\n```\n\n\n:::\n:::\n\n\n\nThere are slightly more males (51%) than females in this sample.\n\n## m1: Descriptive statistics for fev\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npulmonary |>\n  summarize(\n    fev_mn=mean(fev),\n    fev_sd=sd(fev),\n    fev_min=min(fev),\n    fev_max=max(fev))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  fev_mn fev_sd fev_min fev_max\n   <dbl>  <dbl>   <dbl>   <dbl>\n1   2.64  0.867   0.791    5.79\n```\n\n\n:::\n:::\n\n\n\nThe average fev value, 2.6, seems reasonable. The standard deviation, 0.87, indicates a fair amount of variation. The minimum and maximum values both appear to be reasonable.\n\n## m1: Tabular summary of the relationship between sex and fev, 1\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npulmonary |>\n  group_by(sex) |>\n\tsummarize(\n\t\tfev_mn=mean(fev),\n\t\tfev_sd=sd(fev))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  sex   fev_mn fev_sd\n  <chr>  <dbl>  <dbl>\n1 F       2.45  0.646\n2 M       2.81  1.00 \n```\n\n\n:::\n:::\n\n\n\nThe average fev is 0.36 liters higher for males than females. There is very slightly more variation in the males (the standard deviation is 1.00 versus 0.65).\n\n## m1: Graphical summary of the relationship between sex and fev, 2\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npulmonary |>\n  ggplot(aes(sex, fev)) +\n    geom_boxplot() + \n    coord_flip() +\n    ggtitle(\"Graph drawn by Steve Simon on 2024-09-26\") +\n\t  xlab(\"Sex\") +\n\t  ylab(\"Forced Expiratory Volume (liters)\")\n```\n\n::: {.cell-output-display}\n![](simon-5501-07-fev_files/figure-html/sex-and-fev-2-1.png){width=672}\n:::\n:::\n\n\n\nThe boxplot shows the same pattern slightly larger fev values for males compared to females and slightly more variation. \n\n## m1: Fit the linear regression model\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1 <- lm(fev ~ sex, data=pulmonary)\nm1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = fev ~ sex, data = pulmonary)\n\nCoefficients:\n(Intercept)         sexM  \n     2.4512       0.3613  \n```\n\n\n:::\n:::\n\n\n\nThe estimated average fev is 2.45 for females and 0.36 inches higher for males.\n\n## m1: Analysis of variance table\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: fev\n           Df Sum Sq Mean Sq F value    Pr(>F)    \nsex         1  21.32 21.3240  29.607 7.496e-08 ***\nResiduals 652 469.60  0.7202                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\nThe F-statistic, 29.6, is large, and the p-value is very small (< 0.001). Reject the null hypothesis and conclude that the average fev values are different between males and females.\n\n## m1: R-squared\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglance(m1)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0434368\n```\n\n\n:::\n:::\n\n\n\nSex is a very weak predictor of fev. Only 4% of the variation in fev values can be accounted for by a patient's sex.\n\n## m1: Confidence intervals\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                2.5 %   97.5 %\n(Intercept) 2.3577197 2.544620\nsexM        0.2309002 0.491653\n```\n\n\n:::\n:::\n\n\n\nWe are 95% confident that the difference in fev values is between 0.23 and 0.49. This is a positive difference for all values in the confidence interval, demonstrating that the average fev values are larger for males than for females. This interval is narrow indicating that there is very little sampling error. Hardly a surprise with such a large dataset (n=654).\n\n## m1: T-tests\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic   p.value\n  <chr>          <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)    2.45     0.0476     51.5  5.59e-232\n2 sexM           0.361    0.0664      5.44 7.50e-  8\n```\n\n\n:::\n:::\n\n\n\nThe t-statistic, 5.4, is not close to zero. Conclude that there is a difference in average fev values between males and females. Since the t-statistic is positive, conclude also that the average fev value is larger for males.\n\n## m1: Normal probability plot of residuals, 1\n\nNote: I learn something new everyday. You do not have to use qqnorm to create a normal probability plot. You can do it using the ggplot and stat_qq functions. This looks nicer, is consistent with other visualizations in R, and allows you to put in a title using ggtitle. In your homework, you are welcome to use this approach (ggplot and stat_qq) or you can use qqnorm.\n\n## m1: Normal probability plot of residuals, 2\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr1 <- augment(m1)\nr1 |>\n\tggplot(aes(sample=.resid)) +\n\t  stat_qq() +\n    ggtitle(\"Graph drawn by Steve Simon on 2024-09-30\")\n```\n\n::: {.cell-output-display}\n![](simon-5501-07-fev_files/figure-html/m1-qq-plot-1.png){width=672}\n:::\n:::\n\n\n\nThe straight lines indicates that the residuals are normally distributed.\n\n## m1: Histogram of residuals\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr1 |>\n\tggplot(aes(.resid)) +\n\t  geom_histogram(\n\t  \tbinwidth=0.2,\n\t  \tcolor=\"black\",\n\t  \tfill=\"white\") +\n    ggtitle(\"Graph drawn by Steve Simon on 2024-09-26\") +\n\t  xlab(\"Residuals from m1 regression model\")\n```\n\n::: {.cell-output-display}\n![](simon-5501-07-fev_files/figure-html/m1-histogram-1.png){width=672}\n:::\n:::\n\n\n\nThe histogram also indicates that the residuals are normally distributed.\n\n## m1: Influential data points\n\nBoth leverage and Cook's distance make little sense for a regression model using a categorical independent variable. The studentized deleted residual is still useful.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr1 |>\n\tfilter(abs(.std.resid) > 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 8\n    fev sex   .fitted .resid    .hat .sigma .cooksd .std.resid\n  <dbl> <chr>   <dbl>  <dbl>   <dbl>  <dbl>   <dbl>      <dbl>\n1  5.79 M        2.81   2.98 0.00298  0.841  0.0185       3.52\n2  5.63 M        2.81   2.82 0.00298  0.842  0.0165       3.33\n3  5.64 M        2.81   2.83 0.00298  0.842  0.0166       3.33\n```\n\n\n:::\n:::\n\n\n\nThere are three outliers on the high end, corresponding to fev values of 5.6, 5.6, and 5.8 liters in males. There are no outliers among the female patients.\n\n## m2: Linear regression model using smoke to predict fev\n\nIs there a relationship between smoke and fev? This section (labeled m2) shows some simple descriptive and graphical summaries followed by a linear regression model.\n\n## m2: Descriptive statistics for smoke\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npulmonary |>\n\tcount(smoke) |>\n\tmutate(total=sum(n)) |>\n\tmutate(pct=100*n/total)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  smoke     n total   pct\n  <chr> <int> <int> <dbl>\n1 N       589   654 90.1 \n2 Y        65   654  9.94\n```\n\n\n:::\n:::\n\n\n\nThere are very few smokers (65 or 10%) in this sample. Descriptive statistics for fev were shown earlier.\n\n## m2: Relationship between smoke and fev, 1\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npulmonary |>\n  group_by(smoke) |>\n\tsummarize(\n\t\tfev_mn=mean(fev),\n\t\tfev_sd=sd(fev))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  smoke fev_mn fev_sd\n  <chr>  <dbl>  <dbl>\n1 N       2.57  0.851\n2 Y       3.28  0.750\n```\n\n\n:::\n:::\n\n\n\nSmokers have an average fev value that is 0.7 units higher than non-smokers. The standard deviations (0.85 and 0.75) demonstrate roughly the same amount of variation in the two groups.\n\n## m2: Relationship between smoke and fev, 2\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npulmonary |>\n  ggplot(aes(smoke, fev)) +\n    geom_boxplot() + \n    coord_flip() +\n    ggtitle(\"Graph drawn by Steve Simon on 2024-09-26\") +\n\t  xlab(\"Did the patient smoke?\") +\n\t  ylab(\"Forced Expiratory Volume (liters)\")\n```\n\n::: {.cell-output-display}\n![](simon-5501-07-fev_files/figure-html/smoke-and-fev-2-1.png){width=672}\n:::\n:::\n\n\n\nThe boxplot shows the same pattern as noted above.\n\n## m2: Fit the linear regression model\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm2 <- lm(fev ~ smoke, data=pulmonary)\nm2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = fev ~ smoke, data = pulmonary)\n\nCoefficients:\n(Intercept)       smokeY  \n     2.5661       0.7107  \n```\n\n\n:::\n:::\n\n\n\nThe estimated average fev is 2.57 liters for non-smokers and 0.71 liters higher on average for smokers.\n\nNormally, you would follow this up with various functions (anova, confint, tidy), assess various diagnostic plots using the residuals, and identify influential data points.\n\n## m3: Linear regression model using age and height to predict fev\n\nPrevious analysis has shown that age by itself is a strong predictor of fev and height by itself is a strong predictor of fev. A multiple linear regression model including both age and height should do an even better job in predicting fev. This model will also allow you to compare the relative importance of the two variables. Is fev most strongly associated with how big a child is or how old that child is?\n\nYou should always start with descriptive statistics and graphs. With two or more independent variables, you should also examine the correlations between the independent variables and their correlations with the dependent variable.\n\n## m3: Descriptive statistics for age\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npulmonary |>\n  summarize(\n    age_mn=mean(age),\n    age_sd=sd(age),\n    age_min=min(age),\n    age_max=max(age))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  age_mn age_sd age_min age_max\n   <dbl>  <dbl>   <dbl>   <dbl>\n1   9.93   2.95       3      19\n```\n\n\n:::\n:::\n\n\n\nThe descriptive statistics are consistent with a pediatric study. The average age is 9.9 years. The standard deviation, 3.0, shows a large amount of variation in age (large at least for a pediatric study). The range, 3 years to 19 years, also demonstrates a large amount of variation.\n\n## m3: Descriptive statistics for height\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npulmonary |>\n  summarize(\n    ht_mn=mean(height),\n    ht_sd=sd(height),\n    ht_min=min(height),\n    ht_max=max(height))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  ht_mn ht_sd ht_min ht_max\n  <dbl> <dbl>  <dbl>  <dbl>\n1  61.1  5.70     46     74\n```\n\n\n:::\n:::\n\n\n\nThe average height, 61 inches, is reasonable for a group of children with an average age of around 10 years. The standard deviation, 5.7 inches, and the range, 46 inches to 74 inches, show a moderate amount of variation.\n\n## m3: Correlations\n\nReduce the pulmonary data frame to just the first three columns before computing correlations.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npulmonary |>\n  select(height, age, fev) |> \n  cor()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          height       age      fev\nheight 1.0000000 0.7919436 0.868135\nage    0.7919436 1.0000000 0.756459\nfev    0.8681350 0.7564590 1.000000\n```\n\n\n:::\n:::\n\n\n\nThe two independent variables, age and ht, are both strongly correlated with fev (r=0.76 and 0.87). They are also strongly correlated with one another (r=0.79).\n\n## m3: Predicting fev using age and ht\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm3 <- lm(fev ~ age + height, data=pulmonary)\nm3\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = fev ~ age + height, data = pulmonary)\n\nCoefficients:\n(Intercept)          age       height  \n   -4.61047      0.05428      0.10971  \n```\n\n\n:::\n:::\n\n\n\nThe estimated average fev value increases by 0.05 liters for each increase of one year in age, holding height constant. The estimated average fev value increases by 0.11 liters for every increase of one inch in height. The estimated average fev is -4.6 for a patient of age zero with a height of zero inches. This is clearly and extrapolation beyond the range of the data.\n\n## m3: Confidence intervals, 1\n\nThe use of [2, ] (and of [3, ]) isolates the individual rows of the data frame produced by confint. This is not really necessary, but is done to fit the information easily on separate slides.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm3\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = fev ~ age + height, data = pulmonary)\n\nCoefficients:\n(Intercept)          age       height  \n   -4.61047      0.05428      0.10971  \n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(m3)[2, ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     2.5 %     97.5 % \n0.03639976 0.07216159 \n```\n\n\n:::\n:::\n\n\n\nWe are 95% confident that the estimated average fev value increases between 0.036 and 0.072 liters for each increase of one year of age holding height constant. Conclude that there is a positive relationship between fev and age.\n\n## m3: Confidence intervals, 2\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(m3)[3, ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    2.5 %    97.5 % \n0.1004510 0.1189726 \n```\n\n\n:::\n:::\n\n\n\nWe are 95% confident that the estimated average fev value increases between 0.10 and 0.12 liters for each increase of one inch in patient's height holding age constant. Conclude that there is a positive relationship between height and fev.\n\nDo not interpret the confidence interval for the intercept.\n\n## m3: Analysis of variance table\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(m3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: fev\n           Df  Sum Sq Mean Sq F value    Pr(>F)    \nage         1 280.919 280.919 1594.76 < 2.2e-16 ***\nheight      1  95.326  95.326  541.16 < 2.2e-16 ***\nResiduals 651 114.675   0.176                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\nThe sum of squares total (SST) is 280.9 + 95.3 + 114.7 = 490.9. Only a small portion of the variation (114.7) is unexplained variation. The F-ratio is much larger than 1, and the p-value is less than 0.001. You can conclude that the combination of age and height helps significantly in predicting fev.\n\n## m3: R-squared\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglance(m3)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7664081\n```\n\n\n:::\n:::\n\n\n\nRoughly 77% of the variation in fev can be explained by the combination of the age and height of the patients.\n\n## m3: t-tests\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(m3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)  -4.61     0.224      -20.6  9.46e-73\n2 age           0.0543   0.00911      5.96 4.11e- 9\n3 height        0.110    0.00472     23.3  1.38e-87\n```\n\n\n:::\n:::\n\n\n\n## m3: Diagnostic plots, 1\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr3 <- augment(m3)\nr3 |>\n\tggplot(aes(sample=.resid)) +\n\t  stat_qq() +\n    ggtitle(\"Graph drawn by Steve Simon on 2024-09-30\")\n```\n\n::: {.cell-output-display}\n![](simon-5501-07-fev_files/figure-html/diagnostic-1-1.png){width=672}\n:::\n:::\n\n\n\n## m3: Diagnostic plots, 2\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr3 |>\n  ggplot(aes(.resid)) +\n    geom_histogram(\n      binwidth=0.2,\n      color=\"black\",\n      fill=\"white\") +\n    xlab(\"Residuals from m3 regression\") +\n    ggtitle(\"Graph drawn by Steve Simon on 2024-09-25\")\n```\n\n::: {.cell-output-display}\n![](simon-5501-07-fev_files/figure-html/diagnostic-2-1.png){width=672}\n:::\n:::\n\n\n\n## m3: Diagnostic plots, 3\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr3 |>\n  ggplot(aes(.fitted, .resid)) +\n    geom_point() +\n    xlab(\"Predicted values from m3 regression\") +\n    ylab(\"Residuals from m3 regression\") +\n    ggtitle(\"Graph drawn by Steve Simon on 2024-09-25\")\n```\n\n::: {.cell-output-display}\n![](simon-5501-07-fev_files/figure-html/diagnostic-3-1.png){width=672}\n:::\n:::\n\n\n\n## m3: Influential data points, 1\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- nrow(r3)\nr3 |> filter(.hat > 3*3/n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 15 × 9\n     fev   age height .fitted  .resid   .hat .sigma  .cooksd .std.resid\n   <dbl> <dbl>  <dbl>   <dbl>   <dbl>  <dbl>  <dbl>    <dbl>      <dbl>\n 1  1.16     7   47     0.926  0.239  0.0148  0.420 0.00165       0.574\n 2  2.91    18   66     3.61  -0.702  0.0200  0.419 0.0194       -1.69 \n 3  5.10    19   72     4.32   0.782  0.0171  0.419 0.0205        1.88 \n 4  3.52    19   66     3.66  -0.143  0.0262  0.420 0.00107      -0.345\n 5  3.34    19   65.5   3.61  -0.262  0.0274  0.420 0.00376      -0.633\n 6  3.08    18   64.5   3.44  -0.361  0.0231  0.420 0.00598      -0.870\n 7  2.90    16   63     3.17  -0.267  0.0150  0.420 0.00208      -0.641\n 8  4.22    18   68     3.83   0.393  0.0167  0.420 0.00506       0.944\n 9  3.5     17   62     3.11   0.386  0.0228  0.420 0.00672       0.929\n10  2.61    16   62     3.06  -0.452  0.0170  0.420 0.00679      -1.09 \n11  4.09    18   67     3.72   0.369  0.0183  0.420 0.00487       0.887\n12  4.40    18   70.5   4.10   0.303  0.0141  0.420 0.00251       0.726\n13  2.28    15   60     2.79  -0.508  0.0160  0.420 0.00810      -1.22 \n14  2.85    18   60     2.95  -0.0963 0.0359  0.420 0.000678     -0.234\n15  2.80    16   63     3.17  -0.375  0.0150  0.420 0.00410      -0.900\n```\n\n\n:::\n:::\n\n\n\n\n\n## m3: Influential data points, 2\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr3 |> \n  filter(abs(.std.resid) > 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 9\n    fev   age height .fitted .resid    .hat .sigma .cooksd .std.resid\n  <dbl> <dbl>  <dbl>   <dbl>  <dbl>   <dbl>  <dbl>   <dbl>      <dbl>\n1  1.72     8   67.5    3.23  -1.51 0.0131   0.416  0.0578      -3.61\n2  5.22    12   70      3.72   1.50 0.00637  0.416  0.0276       3.59\n3  2.54    14   71      3.94  -1.40 0.00610  0.416  0.0229      -3.35\n4  2.22    13   68      3.56  -1.34 0.00377  0.417  0.0129      -3.20\n5  5.79    15   69      3.77   2.02 0.00604  0.412  0.0472       4.83\n6  5.63    17   73      4.32   1.31 0.0104   0.417  0.0347       3.14\n7  5.64    17   70      3.99   1.65 0.0108   0.415  0.0565       3.94\n```\n\n\n:::\n:::\n\n\n\n## m3: Influential data points, 3\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr3 |> \n  filter(.cooksd > 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 0 × 9\n# ℹ 9 variables: fev <dbl>, age <dbl>, height <dbl>, .fitted <dbl>,\n#   .resid <dbl>, .hat <dbl>, .sigma <dbl>, .cooksd <dbl>, .std.resid <dbl>\n```\n\n\n:::\n:::\n\n\n\n## m3: Variance inflation factor\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(car)\nvif(m3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     age   height \n2.682221 2.682221 \n```\n\n\n:::\n:::",
    "supporting": [
      "simon-5501-07-fev_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}