{
  "hash": "3fcc2c078dea138e46326d045de6d23e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Analysis of Titanic dataset\"\nformat: \n  html:\n    embed-resources: true\n---\n\n\n\nThis program reads data on survival of passengers on the Titanic. Find more\ninformation in the [data dictionary][dd].\n\n[dd]: https://github.com/pmean/data/blob/main/files/titanic.yaml\n\nThis code was written by Steve Simon on 2024-11-09 and is placed in the public\ndomain.\n\n## Load the tidyverse library\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(epitools)\nlibrary(tidyverse)\n```\n:::\n\n\n\n#### Comments on the code\n\nFor most of your programs, you should load the [tidyverse library][tid1]. The \nmessages and warnings are suppressed.\n\n[tid1]: https://www.tidyverse.org/\n\nIn previous programs, I put a label for each chunk inside the curly braces ({}).\nIt is recommended instead to put the label on a separate line inside the program\nchunk. It is a bit more work to provide a unique label for each chunk, but it\nhelps quite a bit to isolate where to look when your code produces an error.\n\n## Read the data and view a brief summary\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nti <- read_tsv(\n  file=\"../data/titanic.txt\",\n  col_names=TRUE,\n  col_types=\"ccncn\",\n  na=\"NA\")\nnames(ti) <- tolower(names(ti))\nglimpse(ti)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,313\nColumns: 5\n$ name     <chr> \"Allen, Miss Elisabeth Walton\", \"Allison, Miss Helen Loraine\"…\n$ pclass   <chr> \"1st\", \"1st\", \"1st\", \"1st\", \"1st\", \"1st\", \"1st\", \"1st\", \"1st\"…\n$ age      <dbl> 29.00, 2.00, 30.00, 25.00, 0.92, 47.00, 63.00, 39.00, 58.00, …\n$ sex      <chr> \"female\", \"female\", \"male\", \"female\", \"male\", \"male\", \"female…\n$ survived <dbl> 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1…\n```\n\n\n:::\n:::\n\n\n\n#### Comments on the code\n\nUse read_tsv from the [readr package][rea1] to  read this file. Use \ncol_names=TRUE because the column names are included as the first row of the \nfile. The col_types=\"ccncn\" specifies the first second and fourth columns as\nstrings and the third and fifth as numeric. There are missing values in this\ndataset, designated by the letters \"NA\".\n\n[rea1]: https://readr.tidyverse.org/\n\n## Replace numeric codes for survived\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nti$survived <-\n\tfactor(\n\t\tti$survived,\n\t\tlevel=1:0,\n\t\tlabels=c(\"yes\", \"no\"))\n```\n:::\n\n\n\n## Get counts of sex by survival\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable1 <-xtabs(~sex+survived, data=ti)\ntable1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        survived\nsex      yes  no\n  female 308 154\n  male   142 709\n```\n\n\n:::\n:::\n\n\n\n#### Comments on the code\n\nThe [table function][tab1] or the [xtabs function][xta1] creates a matrix with \nthe number of observations in each combination of sex and survived. These \nvalues are placed in a single column. The [xtabs function][xta1] or the\n[count function][cou1] provide slightly different approaches.\n\n[cou1]: https://dplyr.tidyverse.org/reference/count.html\n[tab1]: https://stat.ethz.ch/R-manual/R-devel/library/base/html/table.html\n[xta1]: https://stat.ethz.ch/R-manual/R-devel/library/stats/html/xtabs.html\n\n#### Interpretation of the output\n\nThere are 154 female passengers who died and 308 who survived. There are 709 \nmale passengers who died and 142 who survived.\n\n## Chi-squared test, 1\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1 <- chisq.test(table1, correct=FALSE)\nm1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  table1\nX-squared = 332.06, df = 1, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n#### Comments on the code\n\nThe [chisq.test function][chi1] calculates a chi-square test of independence. It\ntakes input in a variety of forms. In this example, it uses a crosstabulation\ncomputed by the xtabs command as input.\n\nThis function also will run a goodness-of-fit test, which is not discussed in \nthis lecture.\n\n[chi1]: https://stat.ethz.ch/R-manual/R-devel/library/stats/html/chisq.test.html\n\n#### Interpretation of the output\n\nThe chi-squared statistic is much larger than the degrees of freedom and the\np-value is small. You should reject the null hypothesis and conclude that sex\nand survival are related (not independent)\n\n## Chi-squared test, 2\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1$observed\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        survived\nsex      yes  no\n  female 308 154\n  male   142 709\n```\n\n\n:::\n:::\n\n\n\n## Chi-squared test, 3\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1$expected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        survived\nsex           yes       no\n  female 158.3397 303.6603\n  male   291.6603 559.3397\n```\n\n\n:::\n:::\n\n\n\n## Fisher's Exact test\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfisher.test(table1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tFisher's Exact Test for Count Data\n\ndata:  table1\np-value < 2.2e-16\nalternative hypothesis: true odds ratio is not equal to 1\n95 percent confidence interval:\n  7.601263 13.122462\nsample estimates:\nodds ratio \n  9.965185 \n```\n\n\n:::\n:::\n\n\n\n#### Comments on the code\n\nThe [fisher.test function][fis1] calculates the Fisher's exact test, which is\nhelpful for small sample sizes. The 1,313 passengers on the Titanic do not\nconstitute a small sample size by any means. This test is just shown as an \nexample of how to calculate this test. \n\n[fis1]: https://stat.ethz.ch/R-manual/R-devel/library/stats/html/fisher.test.html\n\n#### Interpretation of the output\n\nThe p-value is small. You should reject the null hypothesis and conclude that \nsex and survival are related (not independent). The estimated odds ratio is \n9.97. The confidence interval for the odds ratio excludes the value of 1 \nleading to the same conclusion. In fact, even after allowing for sampling error\nthat odds of survival are at least 7.6 times greater for women than for me.\n\n## Odds ratio calculation\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\noddsratio(table1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$data\n        survived\nsex      yes  no Total\n  female 308 154   462\n  male   142 709   851\n  Total  450 863  1313\n\n$measure\n        odds ratio with 95% C.I.\nsex      estimate    lower    upper\n  female 1.000000       NA       NA\n  male   9.956188 7.662525 13.00928\n\n$p.value\n        two-sided\nsex      midp.exact fisher.exact   chi.square\n  female         NA           NA           NA\n  male            0 4.826448e-74 3.425855e-74\n\n$correction\n[1] FALSE\n\nattr(,\"method\")\n[1] \"median-unbiased estimate & mid-p exact CI\"\n```\n\n\n:::\n:::\n\n\n\n#### Comments on the code\n\nThe oddsratio function and riskratio function (see below) are part of the \n[epitools library][epi1]. It produces an odds ratio and confidence interval \nand p-values associated with the Fisher's Exact test and the Chi-squared test of\nindependence.\n\n[epi1]: https://cran.r-project.org/web/packages/epitools/epitools.pdf\n\n#### Interpretation of the output\n\nWe are 95% confident that the odds ratio of survival for women versus men is at\nleast 7.7 and possibly as large as 13, after accounting for sampling error. \nThis interval excludes the value of 1, so you can conclude that the risk of \ndeath is much higher for men than for women. Equivalently you could conclude \nthat the odds of survival are much higher for women than for men.\n\n## Risk ratio calculation, 1\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable1 |>\n  proportions(\"sex\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        survived\nsex            yes        no\n  female 0.6666667 0.3333333\n  male   0.1668625 0.8331375\n```\n\n\n:::\n:::\n\n\n\n#### Interpretation of the output\n\nBefore calculating the risk ratio, let's look at the row percentages one more \ntime. The probability of survival is around 2/3 for women and about 1/6 for men.\nThis means that the risk ratio from a survival perspective is around 4 (2/3 \ndivided by 1/6). The probability of death is 1/3 for females and about 5/6 for\nmales. The risk ratio from a mortality perspective is 0.4 (1/3 divided by 5/6).\n\n## Risk ratio calculation, 2\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nriskratio(table1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$data\n        survived\nsex      yes  no Total\n  female 308 154   462\n  male   142 709   851\n  Total  450 863  1313\n\n$measure\n        risk ratio with 95% C.I.\nsex      estimate    lower    upper\n  female 1.000000       NA       NA\n  male   2.499412 2.189428 2.853285\n\n$p.value\n        two-sided\nsex      midp.exact fisher.exact   chi.square\n  female         NA           NA           NA\n  male            0 4.826448e-74 3.425855e-74\n\n$correction\n[1] FALSE\n\nattr(,\"method\")\n[1] \"Unconditional MLE & normal approximation (Wald) CI\"\n```\n\n\n:::\n:::\n\n\n\n#### Interpretation of the output\n\nThe risk ratio is comparing the probability of death between men and women. Men \nhave 2.5 times higher probability of death compared to women. The confidence \ninterval excludes the value of 1, indicating a statistically significant \nincrease.\n\n## Risk ratio calculation, 3\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nriskratio(table1, rev=\"columns\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$data\n        survived\nsex       no yes Total\n  female 154 308   462\n  male   709 142   851\n  Total  863 450  1313\n\n$measure\n        risk ratio with 95% C.I.\nsex       estimate     lower     upper\n  female 1.0000000        NA        NA\n  male   0.2502938 0.2125647 0.2947195\n\n$p.value\n        two-sided\nsex      midp.exact fisher.exact   chi.square\n  female         NA           NA           NA\n  male            0 4.826448e-74 3.425855e-74\n\n$correction\n[1] FALSE\n\nattr(,\"method\")\n[1] \"Unconditional MLE & normal approximation (Wald) CI\"\n```\n\n\n:::\n:::\n\n\n\n#### Interpretation of the output\n\nThe risk ratio is comparing the probability of survival between men and women. \nMen has one-fourth the probability of survival compared to women. The confidence \ninterval excludes the value of 1, indicating that men have a statistically \nsignificantly lower probability of survival compared to women. \n\n## Save data for later use\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsave(ti, file=\"../data/titanic.RData\")\n```\n:::\n\n\n\n#### Comments on the code\n\nIt is usually a good idea to [save][sav1] your data in an RData file to make it\neasier to retrieve this data later (with the [load function][loa1]).\n\n[sav1]: https://stat.ethz.ch/R-manual/R-devel/library/base/html/save.html\n[loa1]: https://stat.ethz.ch/R-manual/R-devel/library/base/html/save.html\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}