{
  "hash": "6bfae6c16679bc3bced32fb743c005d2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Univariate statistics for Legionnaires disease\"\nformat: \n  html:\n    slide-number: true\n    embed-resources: true\neditor: source\nexecute:\n  echo: true\n  message: false\n  warning: false\n---\n\n\n## Data source\n\nThis program uses data from a fictional study of Legionnaires disease and produces some simple univariate statistics: means, standard deviations, and percentiles. There is a [data dictionary][dd] that provides more details about the data. \n\n[dd]: https://github.com/pmean/data/blob/main/files/legionnaires-disease.yaml\n\n## Libraries\n\nHere are the libraries you need for this program.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n:::\n\n\n## Reading the data\n\nHere is the code to read the data and show a glimpse. There are 31 columns total, but I am showing just a few of the columns here.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfn <- \"../data/legionnaires-disease.txt\"\nld_raw_data <- read_tsv(fn, col_types=\"cnn\")\nglimpse(ld_raw_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 8\nColumns: 3\n$ `Room Number` <chr> \"121\", \"163\", \"125\", \"264\", \"233\", \"218\", \"324\", \"325\"\n$ Before        <dbl> 11.8, 8.2, 7.1, 14.0, 10.8, 10.1, 14.6, 14.0\n$ After         <dbl> 10.1, 7.2, 3.8, 12.0, 8.3, 10.5, 12.1, 13.7\n```\n\n\n:::\n:::\n\n\n## Rename, 1\n\nNotice how R encloses the first variable name (Room Number) in back-quotes. This is needed when a variable includes an embedded blank. You should rename this variable at your first opportunity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(ld_raw_data)[1] <- \"Room_Number\"\nglimpse(ld_raw_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 8\nColumns: 3\n$ Room_Number <chr> \"121\", \"163\", \"125\", \"264\", \"233\", \"218\", \"324\", \"325\"\n$ Before      <dbl> 11.8, 8.2, 7.1, 14.0, 10.8, 10.1, 14.6, 14.0\n$ After       <dbl> 10.1, 7.2, 3.8, 12.0, 8.3, 10.5, 12.1, 13.7\n```\n\n\n:::\n:::\n\n\n## Rename, 2\n\nI find that many of the mistakes that I make are due to inconsistencies in how I name variables. Capitalization is one of the biggest problems. So I have gotten into the habit of converting variable names to all lower case. That way I don't have to worry about whether it is \"Before\" or \"before\". Here is the code to convert every capital letter to a lowercase letter.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(ld_raw_data) <- tolower(names(ld_raw_data))\nglimpse(ld_raw_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 8\nColumns: 3\n$ room_number <chr> \"121\", \"163\", \"125\", \"264\", \"233\", \"218\", \"324\", \"325\"\n$ before      <dbl> 11.8, 8.2, 7.1, 14.0, 10.8, 10.1, 14.6, 14.0\n$ after       <dbl> 10.1, 7.2, 3.8, 12.0, 8.3, 10.5, 12.1, 13.7\n```\n\n\n:::\n:::\n\n\n## Calculate means and standard deviations before remediation\n\n\n::: {.cell}\n\n```{.r .cell-code}\nld_raw_data |>\n  summarize(\n    before_mn=mean(before),\n    before_sd=sd(before)) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  before_mn before_sd\n      <dbl>     <dbl>\n1      11.3      2.79\n```\n\n\n:::\n:::\n\n\nThe average colony count per cubic foot before remediation, 11.3, is quite large. The standard deviation, 2.8, represents a moderate amount of variation in this variable.\n\n## Calculate means and standard deviations after remediation\n\n\n::: {.cell}\n\n```{.r .cell-code}\nld_raw_data |>\n  summarize(\n    after_mn=mean(after),\n    after_sd=sd(after)) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  after_mn after_sd\n     <dbl>    <dbl>\n1     9.71     3.18\n```\n\n\n:::\n:::\n\n\nThe average colony count per cubic foot after remediation, 9.7, is still quite large. The standard deviation, 3.2, represents a moderate amount of variation in this variable and is roughly comparable to the variation before remediation.\n\n## Calculate median and range before intervention\n\nYou could also use \"median(before)\" and  \"min(before)\" and \"max(before)\" in the code below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nld_raw_data |>\n  summarize(\n    before_median=quantile(before, probs=0.5),\n    before_min=quantile(before, probs=0), \n    before_max=quantile(before, probs=1)) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  before_median before_min before_max\n          <dbl>      <dbl>      <dbl>\n1          11.3        7.1       14.6\n```\n\n\n:::\n:::\n\n\nThe median colony count before remediation, 11.3, is roughly the same as the mean. The data ranges from 7.1 to 14.6 colonies per cubic centimeter, a fairly wide range.\n\n## Calculate median and range after intervention\n\n\n::: {.cell}\n\n```{.r .cell-code}\nld_raw_data |>\n  summarize(\n    after_q50=quantile(after, probs=0.5),\n    after_min=quantile(after, probs=0), \n    after_max=quantile(after, probs=1)) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  after_q50 after_min after_max\n      <dbl>     <dbl>     <dbl>\n1      10.3       3.8      13.7\n```\n\n\n:::\n:::\n\n\nThe median colony count, 10.3, is slightly lower after remediation. The data range from 3.8 to 13.7 colonies per cubic centimeter and is about as wide as the range before remediation.\n\n## Additional comments\n\nThe names that you choose for the left hand side of the equal sign are arbitrary. You should choose a descriptive name, but you have lots of options. A median of the before and after values could be called\n\n-   Before_median, After_median\n-   Median0, Median1\n-   Second_quartile_A, Second_quartile_B\n-   or many other reasonable choices.\n\n## Calculate a change score\n\nFor data like this with two measurements before and after an intervention, you should compute a change score. The way the computations are done below, a positive value means a reduction in colony counts. Note that any time you make a major change in a dataset, you should save it with a different name. That makes it easier for you to back up if you end up going down a blind alley.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nld_raw_data |>\n  mutate(change=before-after) -> ld_change_scores\nglimpse(ld_change_scores)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 8\nColumns: 4\n$ room_number <chr> \"121\", \"163\", \"125\", \"264\", \"233\", \"218\", \"324\", \"325\"\n$ before      <dbl> 11.8, 8.2, 7.1, 14.0, 10.8, 10.1, 14.6, 14.0\n$ after       <dbl> 10.1, 7.2, 3.8, 12.0, 8.3, 10.5, 12.1, 13.7\n$ change      <dbl> 1.7, 1.0, 3.3, 2.0, 2.5, -0.4, 2.5, 0.3\n```\n\n\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}